#### <center> Todd Bechtel, Alexander Ha, and Christopher Kang
#### <center> CS 559 Project
#### <center> I pledge my honor that I have abided by the Stevens Honor System.

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
test_data = pd.read_csv('test.csv')
train_data = pd.read_csv('train.csv')
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

test_data.head(5)

,Unnamed: 0,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1436,1437,20,RL,60.0,9000,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,NAmes,Norm,Norm,1Fam,1Story,4,6,1971,1971,Gable,CompShg,HdBoard,HdBoard,None,0.0,TA,TA,PConc,TA,TA,No,ALQ,616,Unf,0,248,864,GasA,TA,Y,SBrkr,864,0,0,864,0,0,1,0,3,1,TA,5,Typ,0,NaN,Detchd,1974.0,Unf,2,528,TA,TA,Y,0,0,0,0,0,0,NaN,GdWo,NaN,0,5,2007,WD,Normal,120500
1,959,960,160,FV,24.0,2572,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Somerst,Norm,Norm,Twnhs,2Story,7,5,1999,1999,Hip,CompShg,MetalSd,MetalSd,None,0.0,Gd,TA,PConc,Gd,TA,No,ALQ,604,Unf,0,92,696,GasA,Ex,Y,SBrkr,696,720,0,1416,1,0,2,1,3,1,Gd,6,Typ,0,NaN,Detchd,1999.0,Unf,2,484,TA,TA,Y,0,44,0,0,0,0,NaN,NaN,NaN,0,5,2010,WD,Normal,155000
2,441,442,90,RL,92.0,12108,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Edwards,Norm,Norm,Duplex,1Story,4,4,1955,1955,Gable,CompShg,VinylSd,VinylSd,BrkFace,270.0,TA,TA,CBlock,TA,TA,No,ALQ,133,Unf,0,1307,1440,GasA,TA,N,FuseF,1440,0,0,1440,0,0,2,0,4,2,Fa,8,Typ,0,NaN,NaN,NaN,NaN,0,0,NaN,NaN,Y,0,0,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,118000
3,536,537,60,RL,57.0,8924,Pave,NaN,IR1,Lvl,AllPub,CulDSac,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,1998,1999,Gable,CompShg,VinylSd,VinylSd,None,0.0,TA,TA,PConc,Gd,TA,Av,Unf,0,Unf,0,880,880,GasA,Ex,Y,SBrkr,880,844,0,1724,0,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,1998.0,Fin,2,527,TA,TA,Y,120,155,0,0,0,0,NaN,NaN,NaN,0,7,2008,WD,Normal,188000
4,488,489,190,RL,60.0,10800,Pave,NaN,Reg,Lvl,AllPub,Corner,Gtl,OldTown,Norm,Norm,2fmCon,1.5Fin,5,4,1900,1970,Gable,CompShg,Wd Sdng,Wd Sdng,None,0.0,TA,Fa,CBlock,TA,Fa,No,BLQ,664,Unf,0,290,954,GasA,TA,N,FuseA,1766,648,0,2414,0,0,2,0,3,2,TA,10,Mod,1,Gd,Attchd,1970.0,Unf,2,520,TA,Fa,N,142,0,0,0,0,0,NaN,NaN,NaN,0,5,2006,ConLD,Normal,160000

In [ ]:
train_data.head(5)

,Unnamed: 0,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,64,65,60,RL,NaN,9375,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,1997,1998,Gable,CompShg,VinylSd,VinylSd,BrkFace,573.0,TA,TA,PConc,Gd,TA,No,GLQ,739,Unf,0,318,1057,GasA,Ex,Y,SBrkr,1057,977,0,2034,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,1998.0,RFn,2,645,TA,TA,Y,576,36,0,0,0,0,NaN,GdPrv,NaN,0,2,2009,WD,Normal,219500
1,651,652,70,RL,60.0,9084,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Edwards,Artery,Norm,1Fam,2Story,4,5,1940,1950,Gable,CompShg,MetalSd,MetalSd,None,0.0,TA,TA,CBlock,TA,TA,Mn,Unf,0,Unf,0,755,755,GasA,TA,Y,SBrkr,755,755,0,1510,1,0,1,0,4,1,TA,7,Typ,1,Gd,Detchd,1940.0,Unf,1,296,Fa,Po,P,120,0,0,0,0,0,NaN,MnPrv,NaN,0,10,2009,WD,Normal,108000
2,260,261,80,RL,120.0,19296,Pave,NaN,Reg,Lvl,AllPub,Corner,Gtl,NAmes,Artery,Norm,1Fam,SLvl,6,5,1962,1962,Gable,CompShg,Wd Sdng,Wd Sdng,BrkFace,399.0,TA,TA,CBlock,TA,TA,Gd,Rec,672,ALQ,690,0,1362,GasA,TA,Y,SBrkr,1382,0,0,1382,1,0,1,0,3,1,TA,6,Typ,1,TA,Attchd,1991.0,Unf,2,884,TA,TA,Y,0,0,252,0,0,0,NaN,GdWo,NaN,0,5,2009,WD,Normal,176000
3,1089,1090,120,FV,37.0,3316,Pave,Pave,IR1,Lvl,AllPub,Inside,Gtl,Somerst,Norm,Norm,TwnhsE,1Story,8,5,2005,2005,Gable,CompShg,MetalSd,MetalSd,None,0.0,Gd,TA,PConc,Gd,TA,No,GLQ,1039,Unf,0,208,1247,GasA,Ex,Y,SBrkr,1247,0,0,1247,1,0,1,1,1,1,Gd,4,Typ,1,Gd,Attchd,2005.0,Fin,2,550,TA,TA,Y,0,84,0,0,0,0,NaN,NaN,NaN,0,4,2006,WD,Normal,197000
4,1112,1113,20,RL,73.0,7100,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,5,7,1957,1957,Gable,CompShg,WdShing,Wd Shng,None,0.0,TA,TA,CBlock,TA,TA,No,GLQ,708,Unf,0,108,816,GasA,TA,Y,FuseA,816,0,0,816,1,0,1,0,2,1,TA,5,Typ,0,NaN,Detchd,1957.0,Unf,1,308,TA,TA,Y,0,0,0,0,0,0,NaN,NaN,NaN,0,7,2006,WD,Normal,129900

In [ ]:
train_data.shape

(1022, 82)

In [ ]:
train_data.dtypes

Unnamed: 0         int64
Id                 int64
MSSubClass         int64
MSZoning          object
LotFrontage      float64
LotArea            int64
Street            object
Alley             object
LotShape          object
LandContour       object
Utilities         object
LotConfig         object
LandSlope         object
Neighborhood      object
Condition1        object
Condition2        object
BldgType          object
HouseStyle        object
OverallQual        int64
OverallCond        int64
YearBuilt          int64
YearRemodAdd       int64
RoofStyle         object
RoofMatl          object
Exterior1st       object
Exterior2nd       object
MasVnrType        object
MasVnrArea       float64
ExterQual         object
ExterCond         object
Foundation        object
BsmtQual          object
BsmtCond          object
BsmtExposure      object
BsmtFinType1      object
BsmtFinSF1         int64
BsmtFinType2      object
BsmtFinSF2         int64
BsmtUnfSF          int64
TotalBsmtSF        int64
Heating           object
HeatingQC         object
CentralAir        object
Electrical        object
1stFlrSF           int64
2ndFlrSF           int64
LowQualFinSF       int64
GrLivArea          int64
BsmtFullBath       int64
BsmtHalfBath       int64
FullBath           int64
HalfBath           int64
BedroomAbvGr       int64
KitchenAbvGr       int64
KitchenQual       object
TotRmsAbvGrd       int64
Functional        object
Fireplaces         int64
FireplaceQu       object
GarageType        object
GarageYrBlt      float64
GarageFinish      object
GarageCars         int64
GarageArea         int64
GarageQual        object
GarageCond        object
PavedDrive        object
WoodDeckSF         int64
OpenPorchSF        int64
EnclosedPorch      int64
3SsnPorch          int64
ScreenPorch        int64
PoolArea           int64
PoolQC            object
Fence             object
MiscFeature       object
MiscVal            int64
MoSold             int64
YrSold             int64
SaleType          object
SaleCondition     object
SalePrice          int64
dtype: object

In [ ]:
train_data.isnull().sum()

Unnamed: 0          0
Id                  0
MSSubClass          0
MSZoning            0
LotFrontage       180
LotArea             0
Street              0
Alley             962
LotShape            0
LandContour         0
Utilities           0
LotConfig           0
LandSlope           0
Neighborhood        0
Condition1          0
Condition2          0
BldgType            0
HouseStyle          0
OverallQual         0
OverallCond         0
YearBuilt           0
YearRemodAdd        0
RoofStyle           0
RoofMatl            0
Exterior1st         0
Exterior2nd         0
MasVnrType          7
MasVnrArea          7
ExterQual           0
ExterCond           0
Foundation          0
BsmtQual           29
BsmtCond           29
BsmtExposure       30
BsmtFinType1       29
BsmtFinSF1          0
BsmtFinType2       30
BsmtFinSF2          0
BsmtUnfSF           0
TotalBsmtSF         0
Heating             0
HeatingQC           0
CentralAir          0
Electrical          0
1stFlrSF            0
2ndFlrSF            0
LowQualFinSF        0
GrLivArea           0
BsmtFullBath        0
BsmtHalfBath        0
FullBath            0
HalfBath            0
BedroomAbvGr        0
KitchenAbvGr        0
KitchenQual         0
TotRmsAbvGrd        0
Functional          0
Fireplaces          0
FireplaceQu       480
GarageType         54
GarageYrBlt        54
GarageFinish       54
GarageCars          0
GarageArea          0
GarageQual         54
GarageCond         54
PavedDrive          0
WoodDeckSF          0
OpenPorchSF         0
EnclosedPorch       0
3SsnPorch           0
ScreenPorch         0
PoolArea            0
PoolQC           1017
Fence             824
MiscFeature       990
MiscVal             0
MoSold              0
YrSold              0
SaleType            0
SaleCondition       0
SalePrice           0
dtype: int64

In [ ]:
train_data.describe()

,Unnamed: 0,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageYrBlt,GarageCars,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1022.000000,1022.000000,1022.000000,842.000000,1022.000000,1022.000000,1022.000000,1022.000000,1022.000000,1015.000000,1022.000000,1022.000000,1022.000000,1022.000000,1022.000000,1022.000000,1022.000000,1022.000000,1022.000000,1022.000000,1022.000000,1022.000000,1022.000000,1022.000000,1022.000000,1022.000000,968.000000,1022.000000,1022.000000,1022.000000,1022.000000,1022.000000,1022.000000,1022.000000,1022.000000,1022.000000,1022.000000,1022.000000,1022.000000
mean,729.223092,730.223092,56.149706,70.261283,10306.330724,6.112524,5.564579,1971.557730,1984.930528,102.175369,443.432485,47.929550,568.239726,1059.601761,1166.794521,337.803327,5.755382,1510.353229,0.430528,0.057730,1.566536,0.375734,2.863992,1.041096,6.504892,0.614481,1978.457645,1.774951,472.549902,93.991194,44.808219,20.854207,3.811155,15.141879,2.869863,29.015656,6.389432,2007.820939,181123.119374
std,428.530232,428.530232,41.215899,24.847801,9635.841640,1.404505,1.110557,29.823413,20.930978,179.987735,461.804349,161.199583,444.253839,457.327726,397.709284,428.528123,46.359630,516.531047,0.518575,0.241595,0.544742,0.500458,0.800401,0.203481,1.587622,0.642980,25.058118,0.735446,209.407113,125.412155,62.973390,60.358181,31.177269,55.037574,41.479727,310.960859,2.728133,1.313022,81038.559207
min,0.000000,1.000000,20.000000,21.000000,1477.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,0.000000,0.000000,0.000000,334.000000,0.000000,0.000000,334.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,1900.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,35311.000000
25%,351.250000,352.250000,20.000000,60.000000,7500.000000,5.000000,5.000000,1953.000000,1966.000000,0.000000,0.000000,0.000000,218.500000,785.000000,874.250000,0.000000,0.000000,1134.250000,0.000000,0.000000,1.000000,0.000000,2.000000,1.000000,5.000000,0.000000,1962.000000,1.000000,336.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129125.000000
50%,740.000000,741.000000,50.000000,70.000000,9410.500000,6.000000,5.000000,1972.000000,1994.000000,0.000000,383.500000,0.000000,485.000000,991.000000,1088.000000,0.000000,0.000000,1471.000000,0.000000,0.000000,2.000000,0.000000,3.000000,1.000000,6.000000,1.000000,1980.000000,2.000000,480.000000,0.000000,24.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,165000.000000
75%,1099.750000,1100.750000,70.000000,80.000000,11433.250000,7.000000,6.000000,2001.000000,2004.000000,164.500000,701.500000,0.000000,798.000000,1311.500000,1411.750000,723.750000,0.000000,1775.750000,1.000000,0.000000,2.000000,1.000000,3.000000,1.000000,7.000000,1.000000,2003.000000,2.000000,576.000000,168.000000,65.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,213500.000000
max,1459.000000,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,1127.000000,2336.000000,6110.000000,4692.000000,2065.000000,514.000000,5642.000000,3.000000,2.000000,3.000000,2.000000,6.000000,2.000000,12.000000,3.000000,2010.000000,4.000000,1418.000000,736.000000,502.000000,552.000000,508.000000,396.000000,738.000000,8300.000000,12.000000,2010.000000,755000.000000

In [ ]:
train_data.corr()["SalePrice"].sort_values()

<ipython-input-10-4982bcdc2618>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  train_data.corr()["SalePrice"].sort_values()

KitchenAbvGr    -0.132590
EnclosedPorch   -0.128401
OverallCond     -0.083465
LowQualFinSF    -0.079848
MSSubClass      -0.076696
Unnamed: 0      -0.035452
Id              -0.035452
MiscVal         -0.029293
YrSold          -0.024045
BsmtHalfBath    -0.015511
BsmtFinSF2      -0.004278
3SsnPorch        0.032842
MoSold           0.060779
ScreenPorch      0.103018
PoolArea         0.116425
BedroomAbvGr     0.175139
BsmtUnfSF        0.218188
BsmtFullBath     0.226761
LotArea          0.257302
HalfBath         0.284235
WoodDeckSF       0.308526
2ndFlrSF         0.308750
OpenPorchSF      0.317960
LotFrontage      0.349727
BsmtFinSF1       0.398335
MasVnrArea       0.475568
Fireplaces       0.475610
GarageYrBlt      0.483741
YearRemodAdd     0.510283
YearBuilt        0.542773
TotRmsAbvGrd     0.555989
FullBath         0.570163
1stFlrSF         0.611725
TotalBsmtSF      0.612676
GarageArea       0.626319
GarageCars       0.634395
GrLivArea        0.719985
OverallQual      0.789634
SalePrice        1.000000
Name: SalePrice, dtype: float64

In [ ]:
train_data['MSZoning'] = np.where(train_data['MSZoning'] == 'RL', 0, train_data['MSZoning'])
train_data['MSZoning'] = np.where(train_data['MSZoning'] == 'RM', 1, train_data['MSZoning'])
train_data['MSZoning'] = np.where(train_data['MSZoning'] == 'FV', 2, train_data['MSZoning'])
train_data['MSZoning'] = np.where(train_data['MSZoning'] == 'RH', 3, train_data['MSZoning'])
train_data['MSZoning'] = np.where(train_data['MSZoning'] == 'C (all)', 4, train_data['MSZoning'])

train_data['MSZoning'].value_counts()

0    808
1    147
2     47
3     13
4      7
Name: MSZoning, dtype: int64

In [ ]:
train_data['MasVnrArea'].fillna(train_data['MasVnrArea'].mean(), inplace=True)

In [ ]:
train_data['GarageYrBlt'].fillna(train_data['GarageYrBlt'].mean(), inplace=True)

In [ ]:
train_data['LotFrontage'].fillna(train_data['LotFrontage'].mean(), inplace=True)

In [ ]:
train_data['Street'] = np.where(train_data['Street'] == 'Pave', 0, train_data['Street'])
train_data['Street'] = np.where(train_data['Street'] == 'Grvl', 1, train_data['Street'])

train_data['Street'].value_counts()

0    1017
1       5
Name: Street, dtype: int64

In [ ]:
train_data['LotShape'] = np.where(train_data['LotShape'] == 'Reg', 0, train_data['LotShape'])
train_data['LotShape'] = np.where(train_data['LotShape'] == 'IR1', 1, train_data['LotShape'])
train_data['LotShape'] = np.where(train_data['LotShape'] == 'IR2', 2, train_data['LotShape'])
train_data['LotShape'] = np.where(train_data['LotShape'] == 'IR3', 3, train_data['LotShape'])

train_data['LotShape'].value_counts()

0    647
1    338
2     29
3      8
Name: LotShape, dtype: int64

In [ ]:
train_data['LandContour'] = np.where(train_data['LandContour'] == 'Lvl', 0, train_data['LandContour'])
train_data['LandContour'] = np.where(train_data['LandContour'] == 'Bnk', 1, train_data['LandContour'])
train_data['LandContour'] = np.where(train_data['LandContour'] == 'HLS', 2, train_data['LandContour'])
train_data['LandContour'] = np.where(train_data['LandContour'] == 'Low', 3, train_data['LandContour'])

train_data['LandContour'].value_counts()

0    920
1     41
2     35
3     26
Name: LandContour, dtype: int64

In [ ]:
train_data['LotConfig'] = np.where(train_data['LotConfig'] == 'Inside', 0, train_data['LotConfig'])
train_data['LotConfig'] = np.where(train_data['LotConfig'] == 'Corner', 1, train_data['LotConfig'])
train_data['LotConfig'] = np.where(train_data['LotConfig'] == 'CulDSac', 2, train_data['LotConfig'])
train_data['LotConfig'] = np.where(train_data['LotConfig'] == 'FR2', 3, train_data['LotConfig'])
train_data['LotConfig'] = np.where(train_data['LotConfig'] == 'FR3', 4, train_data['LotConfig'])

train_data['LotConfig'].value_counts()

0    729
1    194
2     68
3     29
4      2
Name: LotConfig, dtype: int64

In [ ]:
train_data['LandSlope'] = np.where(train_data['LandSlope'] == 'Gtl', 0, train_data['LandSlope'])
train_data['LandSlope'] = np.where(train_data['LandSlope'] == 'Mod', 1, train_data['LandSlope'])
train_data['LandSlope'] = np.where(train_data['LandSlope'] == 'Sev', 2, train_data['LandSlope'])

train_data['LandSlope'].value_counts()

0    963
1     52
2      7
Name: LandSlope, dtype: int64

In [ ]:
train_data['Neighborhood'] = np.where(train_data['Neighborhood'] == 'NAmes', 0, train_data['Neighborhood'])
train_data['Neighborhood'] = np.where(train_data['Neighborhood'] == 'CollgCr', 1, train_data['Neighborhood'])
train_data['Neighborhood'] = np.where(train_data['Neighborhood'] == 'Edwards', 2, train_data['Neighborhood'])
train_data['Neighborhood'] = np.where(train_data['Neighborhood'] == 'OldTown', 3, train_data['Neighborhood'])
train_data['Neighborhood'] = np.where(train_data['Neighborhood'] == 'Somerst', 4, train_data['Neighborhood'])
train_data['Neighborhood'] = np.where(train_data['Neighborhood'] == 'Sawyer', 5, train_data['Neighborhood'])
train_data['Neighborhood'] = np.where(train_data['Neighborhood'] == 'NridgHt', 6, train_data['Neighborhood'])
train_data['Neighborhood'] = np.where(train_data['Neighborhood'] == 'Gilbert', 7, train_data['Neighborhood'])
train_data['Neighborhood'] = np.where(train_data['Neighborhood'] == 'NWAmes', 8, train_data['Neighborhood'])
train_data['Neighborhood'] = np.where(train_data['Neighborhood'] == 'SawyerW', 9, train_data['Neighborhood'])
train_data['Neighborhood'] = np.where(train_data['Neighborhood'] == 'BrkSide', 10, train_data['Neighborhood'])
train_data['Neighborhood'] = np.where(train_data['Neighborhood'] == 'Crawfor', 11, train_data['Neighborhood'])
train_data['Neighborhood'] = np.where(train_data['Neighborhood'] == 'Mitchel', 12, train_data['Neighborhood'])
train_data['Neighborhood'] = np.where(train_data['Neighborhood'] == 'Timber', 13, train_data['Neighborhood'])
train_data['Neighborhood'] = np.where(train_data['Neighborhood'] == 'IDOTRR', 14, train_data['Neighborhood'])
train_data['Neighborhood'] = np.where(train_data['Neighborhood'] == 'NoRidge', 15, train_data['Neighborhood'])
train_data['Neighborhood'] = np.where(train_data['Neighborhood'] == 'ClearCr', 16, train_data['Neighborhood'])
train_data['Neighborhood'] = np.where(train_data['Neighborhood'] == 'SWISU', 17, train_data['Neighborhood'])
train_data['Neighborhood'] = np.where(train_data['Neighborhood'] == 'StoneBr', 18, train_data['Neighborhood'])
train_data['Neighborhood'] = np.where(train_data['Neighborhood'] == 'Blmngtn', 19, train_data['Neighborhood'])
train_data['Neighborhood'] = np.where(train_data['Neighborhood'] == 'MeadowV', 20, train_data['Neighborhood'])
train_data['Neighborhood'] = np.where(train_data['Neighborhood'] == 'BrDale', 21, train_data['Neighborhood'])
train_data['Neighborhood'] = np.where(train_data['Neighborhood'] == 'Veenker', 22, train_data['Neighborhood'])
train_data['Neighborhood'] = np.where(train_data['Neighborhood'] == 'NPkVill', 23, train_data['Neighborhood'])

train_data['Neighborhood'].value_counts()

0     159
1     107
2      74
3      73
4      64
5      56
6      55
7      51
8      49
9      43
10     41
11     37
12     29
13     28
14     27
15     25
16     19
17     18
18     17
19     14
20     12
21     11
22     10
23      3
Name: Neighborhood, dtype: int64

In [ ]:
train_data['Condition1'] = np.where(train_data['Condition1'] == 'Norm', 0, train_data['Condition1'])
train_data['Condition1'] = np.where(train_data['Condition1'] == 'Feedr', 1, train_data['Condition1'])
train_data['Condition1'] = np.where(train_data['Condition1'] == 'Artery', 2, train_data['Condition1'])
train_data['Condition1'] = np.where(train_data['Condition1'] == 'RRAn', 3, train_data['Condition1'])
train_data['Condition1'] = np.where(train_data['Condition1'] == 'PosN', 4, train_data['Condition1'])
train_data['Condition1'] = np.where(train_data['Condition1'] == 'RRAe', 5, train_data['Condition1'])
train_data['Condition1'] = np.where(train_data['Condition1'] == 'PosA', 6, train_data['Condition1'])
train_data['Condition1'] = np.where(train_data['Condition1'] == 'RRNn', 7, train_data['Condition1'])
train_data['Condition1'] = np.where(train_data['Condition1'] == 'RRNe', 8, train_data['Condition1'])

train_data['Condition1'].value_counts()

0    875
1     55
2     40
3     18
4     14
5      8
6      7
7      4
8      1
Name: Condition1, dtype: int64

In [ ]:
train_data['Condition2'] = np.where(train_data['Condition2'] == 'Norm', 0, train_data['Condition2'])
train_data['Condition2'] = np.where(train_data['Condition2'] == 'Feedr', 1, train_data['Condition2'])
train_data['Condition2'] = np.where(train_data['Condition2'] == 'Artery', 2, train_data['Condition2'])
train_data['Condition2'] = np.where(train_data['Condition2'] == 'RRAn', 3, train_data['Condition2'])
train_data['Condition2'] = np.where(train_data['Condition2'] == 'PosN', 4, train_data['Condition2'])
train_data['Condition2'] = np.where(train_data['Condition2'] == 'RRAe', 5, train_data['Condition2'])
train_data['Condition2'] = np.where(train_data['Condition2'] == 'PosA', 6, train_data['Condition2'])
train_data['Condition2'] = np.where(train_data['Condition2'] == 'RRNn', 7, train_data['Condition2'])
train_data['Condition2'] = np.where(train_data['Condition2'] == 'RRNe', 8, train_data['Condition2'])

train_data['Condition2'].value_counts()

0    1009
1       5
2       2
7       2
5       1
6       1
4       1
3       1
Name: Condition2, dtype: int64

In [ ]:
train_data['BldgType'] = np.where(train_data['BldgType'] == '1Fam', 0, train_data['BldgType'])
train_data['BldgType'] = np.where(train_data['BldgType'] == 'TwnhsE', 1, train_data['BldgType'])
train_data['BldgType'] = np.where(train_data['BldgType'] == 'Duplex', 2, train_data['BldgType'])
train_data['BldgType'] = np.where(train_data['BldgType'] == 'Twnhs', 3, train_data['BldgType'])
train_data['BldgType'] = np.where(train_data['BldgType'] == '2fmCon', 4, train_data['BldgType'])

train_data['BldgType'].value_counts()

0    861
1     78
2     36
3     28
4     19
Name: BldgType, dtype: int64

In [ ]:
train_data['HouseStyle'] = np.where(train_data['HouseStyle'] == '1Story', 0, train_data['HouseStyle'])
train_data['HouseStyle'] = np.where(train_data['HouseStyle'] == '2Story', 1, train_data['HouseStyle'])
train_data['HouseStyle'] = np.where(train_data['HouseStyle'] == '1.5Fin', 2, train_data['HouseStyle'])
train_data['HouseStyle'] = np.where(train_data['HouseStyle'] == 'SLvl', 3, train_data['HouseStyle'])
train_data['HouseStyle'] = np.where(train_data['HouseStyle'] == 'SFoyer', 4, train_data['HouseStyle'])
train_data['HouseStyle'] = np.where(train_data['HouseStyle'] == '1.5Unf', 5, train_data['HouseStyle'])
train_data['HouseStyle'] = np.where(train_data['HouseStyle'] == '2.5Unf', 6, train_data['HouseStyle'])
train_data['HouseStyle'] = np.where(train_data['HouseStyle'] == '2.5Fin', 7, train_data['HouseStyle'])

train_data['HouseStyle'].value_counts()

0    513
1    299
2    116
3     50
4     24
5      8
6      8
7      4
Name: HouseStyle, dtype: int64

In [ ]:
train_data['RoofStyle'] = np.where(train_data['RoofStyle'] == 'Gable', 0, train_data['RoofStyle'])
train_data['RoofStyle'] = np.where(train_data['RoofStyle'] == 'Hip', 1, train_data['RoofStyle'])
train_data['RoofStyle'] = np.where(train_data['RoofStyle'] == 'Flat', 2, train_data['RoofStyle'])
train_data['RoofStyle'] = np.where(train_data['RoofStyle'] == 'Gambrel', 3, train_data['RoofStyle'])
train_data['RoofStyle'] = np.where(train_data['RoofStyle'] == 'Mansard', 4, train_data['RoofStyle'])
train_data['RoofStyle'] = np.where(train_data['RoofStyle'] == 'Shed', 5, train_data['RoofStyle'])

train_data['RoofStyle'].value_counts()

0    798
1    202
2     10
3      7
4      3
5      2
Name: RoofStyle, dtype: int64

In [ ]:
train_data['RoofMatl'].replace({'CompShg':int(0),'Tar&Grv':int(1),'WdShake':int(2), 'WdShngl':int(3), 'Metal':int(4), 'Membran':int(5), 'ClyTile':int(6)}, inplace=True)
train_data['RoofMatl'].value_counts()

0    1003
1       9
2       4
3       3
4       1
5       1
6       1
Name: RoofMatl, dtype: int64

In [ ]:
train_data['Exterior1st'].replace({'VinylSd':int(0),'HdBoard':int(1),'MetalSd':int(2), 'Wd Sdng':int(3), 'Plywood':int(4), 'CemntBd':int(5), 'BrkFace':int(6), 'WdShing':int(7), 'Stucco':int(8), 'AsbShng':int(9), 'Stone':int(10), 'AsphShn':int(11), 'BrkComm':int(12)}, inplace=True)
train_data['Exterior1st'].value_counts()

0     363
1     160
2     149
3     138
4      73
5      44
6      37
7      23
8      18
9      13
10      2
11      1
12      1
Name: Exterior1st, dtype: int64

In [ ]:
train_data['Exterior2nd'].replace({'VinylSd':int(0),'HdBoard':int(1),'MetalSd':int(2), 'Wd Sdng':int(3), 'Plywood':int(4), 'CmentBd':int(5), 'Wd Shng':int(6), 'BrkFace':int(7), 'Stucco':int(8), 'AsbShng':int(9), 'ImStucc':int(10), 'Stone':int(11), 'Brk Cmn':int(12), 'AsphShn':int(13), 'Other':int(14)}, inplace=True)
train_data['Exterior2nd'].value_counts()

0     352
1     151
2     145
3     136
4      98
5      42
6      31
7      20
8      19
9      15
10      5
11      4
12      2
13      1
14      1
Name: Exterior2nd, dtype: int64

In [ ]:
train_data['MasVnrType'].replace({'None':int(0),'BrkFace':int(1),'Stone':int(2), 'BrkCmn':int(3)}, inplace=True)
train_data['MasVnrType'].fillna(4, inplace=True)
train_data['MasVnrType'].value_counts()

0.0    607
1.0    311
2.0     88
3.0      9
4.0      7
Name: MasVnrType, dtype: int64

In [ ]:
train_data['ExterQual'].replace({'TA':int(0),'Gd':int(1),'Ex':int(2), 'Fa':int(3)}, inplace=True)
train_data['ExterQual'].value_counts()

0    624
1    349
2     40
3      9
Name: ExterQual, dtype: int64

In [ ]:
train_data['ExterCond'].replace({'TA':int(0),'Gd':int(1),'Fa':int(2), 'Ex':int(3), 'Po':int(4)}, inplace=True)
train_data['ExterCond'].value_counts()

0    901
1     97
2     20
3      3
4      1
Name: ExterCond, dtype: int64

In [ ]:
train_data['Foundation'].replace({'PConc':int(0),'CBlock':int(1),'BrkTil':int(2), 'Slab':int(3), 'Stone':int(4), 'Wood':int(5)}, inplace=True)
train_data['Foundation'].value_counts()

0    459
1    438
2     99
3     21
4      3
5      2
Name: Foundation, dtype: int64

In [ ]:
train_data['BsmtQual'].replace({'TA':int(0),'Gd':int(1),'Ex':int(2), 'Fa':int(3)}, inplace=True)
train_data['BsmtQual'].fillna(4, inplace=True)
train_data['BsmtQual'].value_counts()

0.0    453
1.0    425
2.0     87
4.0     29
3.0     28
Name: BsmtQual, dtype: int64

In [ ]:
train_data['BsmtCond'].replace({'TA':int(0),'Gd':int(1),'Fa':int(2), 'Po':int(3)}, inplace=True)
train_data['BsmtCond'].fillna(4, inplace=True)
train_data['BsmtCond'].value_counts()

0.0    913
1.0     47
2.0     31
4.0     29
3.0      2
Name: BsmtCond, dtype: int64

In [ ]:
train_data['BsmtExposure'].replace({'No':int(0),'Av':int(1),'Gd':int(2), 'Mn':int(3)}, inplace=True)
train_data['BsmtExposure'].fillna(4, inplace=True)
train_data['BsmtExposure'].value_counts()

0.0    655
1.0    163
2.0     94
3.0     80
4.0     30
Name: BsmtExposure, dtype: int64

In [ ]:
train_data['BsmtFinType1'].replace({'GLQ':int(0),'Unf':int(1),'ALQ':int(2), 'BLQ':int(3), 'Rec':int(4), 'LwQ':int(5)}, inplace=True)
train_data['BsmtFinType1'].fillna(6, inplace=True)
train_data['BsmtFinType1'].value_counts()

0.0    299
1.0    292
2.0    154
3.0    102
4.0     95
5.0     51
6.0     29
Name: BsmtFinType1, dtype: int64

In [ ]:
train_data['BsmtFinType2'].replace({'GLQ':int(0),'Unf':int(1),'ALQ':int(2), 'BLQ':int(3), 'Rec':int(4), 'LwQ':int(5)}, inplace=True)
train_data['BsmtFinType2'].fillna(6, inplace=True)
train_data['BsmtFinType2'].value_counts()

1.0    874
4.0     43
6.0     30
5.0     28
3.0     22
2.0     13
0.0     12
Name: BsmtFinType2, dtype: int64

In [ ]:
train_data['Heating'] = np.where(train_data['Heating'] == 'GasA', 0, train_data['Heating'])
train_data['Heating'] = np.where(train_data['Heating'] == 'GasW', 1, train_data['Heating'])
train_data['Heating'] = np.where(train_data['Heating'] == 'Grav', 2, train_data['Heating'])
train_data['Heating'] = np.where(train_data['Heating'] == 'Wall', 3, train_data['Heating'])
train_data['Heating'] = np.where(train_data['Heating'] == 'OthW', 4, train_data['Heating'])

train_data['Heating'].value_counts()

0    998
1     13
2      5
3      4
4      2
Name: Heating, dtype: int64

In [ ]:
train_data['HeatingQC'] = np.where(train_data['HeatingQC'] == 'Ex', 0, train_data['HeatingQC'])
train_data['HeatingQC'] = np.where(train_data['HeatingQC'] == 'TA', 1, train_data['HeatingQC'])
train_data['HeatingQC'] = np.where(train_data['HeatingQC'] == 'Gd', 2, train_data['HeatingQC'])
train_data['HeatingQC'] = np.where(train_data['HeatingQC'] == 'Fa', 3, train_data['HeatingQC'])
train_data['HeatingQC'] = np.where(train_data['HeatingQC'] == 'Po', 4, train_data['HeatingQC'])

train_data['HeatingQC'].value_counts()

0    530
1    276
2    178
3     37
4      1
Name: HeatingQC, dtype: int64

In [ ]:
train_data['CentralAir'] = np.where(train_data['CentralAir'] == 'Y', 0, train_data['CentralAir'])
train_data['CentralAir'] = np.where(train_data['CentralAir'] == 'N', 1, train_data['CentralAir'])

train_data['CentralAir'].value_counts()

0    950
1     72
Name: CentralAir, dtype: int64

In [ ]:
train_data['Electrical'] = np.where(train_data['Electrical'] == 'SBrkr', 0, train_data['Electrical'])
train_data['Electrical'] = np.where(train_data['Electrical'] == 'FuseA', 1, train_data['Electrical'])
train_data['Electrical'] = np.where(train_data['Electrical'] == 'FuseF', 2, train_data['Electrical'])
train_data['Electrical'] = np.where(train_data['Electrical'] == 'FuseP', 3, train_data['Electrical'])
train_data['Electrical'] = np.where(train_data['Electrical'] == 'Mix', 4, train_data['Electrical'])

train_data['Electrical'].value_counts()

0    937
1     64
2     18
3      2
4      1
Name: Electrical, dtype: int64

In [ ]:
train_data['KitchenQual'] = np.where(train_data['KitchenQual'] == 'TA', 0, train_data['KitchenQual'])
train_data['KitchenQual'] = np.where(train_data['KitchenQual'] == 'Gd', 1, train_data['KitchenQual'])
train_data['KitchenQual'] = np.where(train_data['KitchenQual'] == 'Ex', 2, train_data['KitchenQual'])
train_data['KitchenQual'] = np.where(train_data['KitchenQual'] == 'Fa', 3, train_data['KitchenQual'])

train_data['KitchenQual'].value_counts()

0    501
1    420
2     73
3     28
Name: KitchenQual, dtype: int64

In [ ]:
train_data['Functional'] = np.where(train_data['Functional'] == 'Typ', 0, train_data['Functional'])
train_data['Functional'] = np.where(train_data['Functional'] == 'Min2', 1, train_data['Functional'])
train_data['Functional'] = np.where(train_data['Functional'] == 'Min1', 2, train_data['Functional'])
train_data['Functional'] = np.where(train_data['Functional'] == 'Mod', 3, train_data['Functional'])
train_data['Functional'] = np.where(train_data['Functional'] == 'Maj1', 4, train_data['Functional'])
train_data['Functional'] = np.where(train_data['Functional'] == 'Maj2', 5, train_data['Functional'])

train_data['Functional'].value_counts()

0    945
1     26
2     25
3     11
4     10
5      5
Name: Functional, dtype: int64

In [ ]:
train_data['FireplaceQu'].replace({'Gd':int(0),'TA':int(1),'Fa':int(2), 'Ex':int(3), 'Po':int(4)}, inplace=True)
train_data['FireplaceQu'].fillna(5, inplace=True)
train_data['FireplaceQu'].value_counts()

5.0    480
0.0    284
1.0    202
2.0     24
3.0     19
4.0     13
Name: FireplaceQu, dtype: int64

In [ ]:
train_data['GarageType'] = np.where(train_data['GarageType'] == 'Attchd', 0, train_data['GarageType'])
train_data['GarageType'] = np.where(train_data['GarageType'] == 'Detchd', 1, train_data['GarageType'])
train_data['GarageType'] = np.where(train_data['GarageType'] == 'BuiltIn', 2, train_data['GarageType'])
train_data['GarageType'] = np.where(train_data['GarageType'] == 'Basment', 3, train_data['GarageType'])
train_data['GarageType'] = np.where(train_data['GarageType'] == 'CarPort', 4, train_data['GarageType'])
train_data['GarageType'] = np.where(train_data['GarageType'] == '2Types', 5, train_data['GarageType'])
train_data['GarageType'].fillna(6, inplace=True)

train_data['GarageType'].value_counts()

0    607
1    277
2     60
6     54
3     14
4      6
5      4
Name: GarageType, dtype: int64

In [ ]:
train_data['GarageFinish'] = np.where(train_data['GarageFinish'] == 'Unf', 0, train_data['GarageFinish'])
train_data['GarageFinish'] = np.where(train_data['GarageFinish'] == 'RFn', 1, train_data['GarageFinish'])
train_data['GarageFinish'] = np.where(train_data['GarageFinish'] == 'Fin', 2, train_data['GarageFinish'])
train_data['GarageFinish'].fillna(3, inplace=True)

train_data['GarageFinish'].value_counts()

0    421
1    303
2    244
3     54
Name: GarageFinish, dtype: int64

In [ ]:
train_data['GarageQual'].replace({'TA':int(0),'Fa':int(1),'Gd':int(2), 'Po':int(3), 'Ex': int(4)}, inplace=True)
train_data['GarageQual'].fillna(5, inplace=True)
train_data['GarageQual'].value_counts()

0.0    918
5.0     54
1.0     35
2.0     11
3.0      2
4.0      2
Name: GarageQual, dtype: int64

In [ ]:
train_data['GarageCond'].replace({'TA':int(0),'Fa':int(1),'Gd':int(2), 'Po':int(3), 'Ex': int(4)}, inplace=True)
train_data['GarageCond'].fillna(5, inplace=True)
train_data['GarageCond'].value_counts()

0.0    933
5.0     54
1.0     23
2.0      6
3.0      4
4.0      2
Name: GarageCond, dtype: int64

In [ ]:
train_data['PavedDrive'].replace({'Y':int(0),'N':int(1),'P':int(2)}, inplace=True)
train_data['PavedDrive'].value_counts()

0    946
1     55
2     21
Name: PavedDrive, dtype: int64

In [ ]:
train_data['Fence'].replace({'MnPrv':int(0),'GdWo':int(1),'GdPrv':int(2), 'MnWw':int(3),}, inplace=True)
train_data['Fence'].fillna(4, inplace=True)
train_data['Fence'].value_counts()

4.0    824
0.0    110
1.0     41
2.0     38
3.0      9
Name: Fence, dtype: int64

In [ ]:
train_data['SaleType'].replace({'WD':int(0),'New':int(1),'COD':int(2), 'CWD':int(3), 'ConLw':int(4), 'ConLD':int(5), 'ConLI':int(6), 'Con':int(7), 'Oth':int(8)}, inplace=True)
train_data['SaleType'].value_counts()

0    890
1     86
2     29
3      4
4      4
5      4
6      2
7      2
8      1
Name: SaleType, dtype: int64

In [ ]:
train_data['SaleCondition'].replace({'Normal':int(0),'Partial':int(1),'Abnorml':int(2), 'Family':int(3), 'Alloca':int(4), 'AdjLand':int(5)}, inplace=True)
train_data['SaleCondition'].value_counts()

0    840
1     88
2     71
3     12
4      9
5      2
Name: SaleCondition, dtype: int64

In [ ]:
train_data['Alley'].replace({'Grvl':int(0),'Pave':int(1)}, inplace=True)
train_data['Alley'].fillna(2, inplace=True)
train_data['Alley'].value_counts()

2.0    962
0.0     35
1.0     25
Name: Alley, dtype: int64

In [ ]:
train_data['Utilities'].value_counts()
train_data['Utilities'].replace({'AllPub':int(0),'NoSeWa':int(1)}, inplace=True)

In [ ]:
train_data['PoolQC'].replace({'Gd':int(0),'Ex':int(1),'Fa':int(2)}, inplace=True)
train_data['PoolQC'].fillna(3, inplace=True)
train_data['PoolQC'].value_counts()

3.0    1017
0.0       2
1.0       2
2.0       1
Name: PoolQC, dtype: int64

In [ ]:
train_data['MiscFeature'].replace({'Shed':int(0),'Othr':int(1),'Gar2':int(2)}, inplace=True)
train_data['MiscFeature'].fillna(3, inplace=True)
train_data['MiscFeature'].value_counts()

3.0    990
0.0     29
1.0      2
2.0      1
Name: MiscFeature, dtype: int64

In [ ]:
train_data = train_data.astype({'MSZoning': int, 'Street': int, 'LotShape': int, 'LandContour': int,
                                'LotConfig': int, 'LandSlope': int, 'Neighborhood': int, 'Condition1': int, 'Condition2': int,
                                'BldgType': int, 'HouseStyle': int, 'RoofStyle': int,
                                'RoofMatl': int, 'Exterior1st': int, 'Exterior2nd': int, 'MasVnrType': int, 'ExterQual': int,
                                'ExterCond': int, 'Foundation': int, 'BsmtQual': int, 'BsmtCond': int, 'BsmtExposure': int, 'BsmtFinType1': int,
                                'BsmtFinType2': int, 'Heating': int, 'HeatingQC': int, 'CentralAir': int,
                                'Electrical': int, 'KitchenQual': int, 'Functional': int, 'FireplaceQu': int,
                                'GarageType': int, 'GarageFinish': int, 'GarageQual': int, 'GarageCond': int,
                                'PavedDrive': int, 'Fence': int, 'SaleType': int, 'SaleCondition': int, 'Alley': int}, errors = 'ignore')

In [ ]:
train_data.isnull().sum()

Unnamed: 0       0
Id               0
MSSubClass       0
MSZoning         0
LotFrontage      0
LotArea          0
Street           0
Alley            0
LotShape         0
LandContour      0
Utilities        0
LotConfig        0
LandSlope        0
Neighborhood     0
Condition1       0
Condition2       0
BldgType         0
HouseStyle       0
OverallQual      0
OverallCond      0
YearBuilt        0
YearRemodAdd     0
RoofStyle        0
RoofMatl         0
Exterior1st      0
Exterior2nd      0
MasVnrType       0
MasVnrArea       0
ExterQual        0
ExterCond        0
Foundation       0
BsmtQual         0
BsmtCond         0
BsmtExposure     0
BsmtFinType1     0
BsmtFinSF1       0
BsmtFinType2     0
BsmtFinSF2       0
BsmtUnfSF        0
TotalBsmtSF      0
Heating          0
HeatingQC        0
CentralAir       0
Electrical       0
1stFlrSF         0
2ndFlrSF         0
LowQualFinSF     0
GrLivArea        0
BsmtFullBath     0
BsmtHalfBath     0
FullBath         0
HalfBath         0
BedroomAbvGr     0
KitchenAbvGr     0
KitchenQual      0
TotRmsAbvGrd     0
Functional       0
Fireplaces       0
FireplaceQu      0
GarageType       0
GarageYrBlt      0
GarageFinish     0
GarageCars       0
GarageArea       0
GarageQual       0
GarageCond       0
PavedDrive       0
WoodDeckSF       0
OpenPorchSF      0
EnclosedPorch    0
3SsnPorch        0
ScreenPorch      0
PoolArea         0
PoolQC           0
Fence            0
MiscFeature      0
MiscVal          0
MoSold           0
YrSold           0
SaleType         0
SaleCondition    0
SalePrice        0
dtype: int64

In [ ]:
abs(train_data.corr()["SalePrice"]).sort_values()

BsmtFinSF2       0.004278
Condition2       0.005742
BsmtHalfBath     0.015511
Utilities        0.016855
YrSold           0.024045
MiscVal          0.029293
3SsnPorch        0.032842
Unnamed: 0       0.035452
Id               0.035452
Street           0.035574
SaleCondition    0.038697
LandSlope        0.048897
Condition1       0.052441
MoSold           0.060779
MSSubClass       0.076696
LandContour      0.078183
LowQualFinSF     0.079848
LotConfig        0.081439
OverallCond      0.083465
MiscFeature      0.083845
SaleType         0.093387
RoofMatl         0.095524
ScreenPorch      0.103018
HouseStyle       0.107521
PoolQC           0.108268
Heating          0.112853
Functional       0.113995
PoolArea         0.116425
EnclosedPorch    0.128401
KitchenAbvGr     0.132590
BsmtExposure     0.135043
BsmtFinType2     0.144896
Alley            0.147255
ExterCond        0.148288
Exterior2nd      0.155927
Exterior1st      0.163790
Neighborhood     0.167104
RoofStyle        0.167533
BldgType         0.170327
BedroomAbvGr     0.175139
MSZoning         0.184245
Fence            0.184656
BsmtCond         0.185337
PavedDrive       0.198381
BsmtUnfSF        0.218188
BsmtFullBath     0.226761
Electrical       0.242300
GarageQual       0.249606
GarageCond       0.256365
LotArea          0.257302
LotShape         0.257914
CentralAir       0.266565
GarageType       0.281113
BsmtQual         0.282423
HalfBath         0.284235
WoodDeckSF       0.308526
2ndFlrSF         0.308750
GarageFinish     0.310054
OpenPorchSF      0.317960
LotFrontage      0.332655
HeatingQC        0.364964
MasVnrType       0.382730
BsmtFinType1     0.384000
BsmtFinSF1       0.398335
KitchenQual      0.448447
FireplaceQu      0.463195
Foundation       0.463273
GarageYrBlt      0.468348
MasVnrArea       0.472504
Fireplaces       0.475610
YearRemodAdd     0.510283
YearBuilt        0.542773
TotRmsAbvGrd     0.555989
FullBath         0.570163
ExterQual        0.574934
1stFlrSF         0.611725
TotalBsmtSF      0.612676
GarageArea       0.626319
GarageCars       0.634395
GrLivArea        0.719985
OverallQual      0.789634
SalePrice        1.000000
Name: SalePrice, dtype: float64

In [ ]:
corrmatrix = train_data.corr()
corrmatrix.style.background_gradient(cmap = 'coolwarm')

In [ ]:
train_data=train_data.drop(['Utilities', 'Id', 'Unnamed: 0', 'PoolQC', 'BsmtFinSF2', 'BsmtHalfBath', 'YrSold', 'MiscVal',
                            '3SsnPorch', 'SaleCondition', 'MoSold', 'BsmtFinType2', 'MSSubClass', 'LowQualFinSF', 'OverallCond',
                            'Fence', 'SaleType', 'RoofMatl', 'BsmtCond', 'ScreenPorch', 'PoolArea', 'BsmtFullBath',
                            'EnclosedPorch', 'Condition2', 'Street', 'LandSlope', 'BsmtExposure', 'Alley', 'PavedDrive', 'BsmtUnfSF',
                            'Condition1', 'LandContour', 'LotConfig', 'HouseStyle', 'Heating', 'Functional', 'KitchenAbvGr',
                            'Exterior2nd', 'Exterior1st', 'ExterCond', 'Neighborhood', 'RoofStyle', 'BldgType', 'BedroomAbvGr',
                            'MSZoning', 'MiscFeature'],axis=1)
train_data.shape

(1022, 36)

In [ ]:
abs(train_data.corr()["SalePrice"]).sort_values()

Electrical      0.242300
GarageQual      0.249606
GarageCond      0.256365
LotArea         0.257302
LotShape        0.257914
CentralAir      0.266565
GarageType      0.281113
BsmtQual        0.282423
HalfBath        0.284235
WoodDeckSF      0.308526
2ndFlrSF        0.308750
GarageFinish    0.310054
OpenPorchSF     0.317960
LotFrontage     0.332655
HeatingQC       0.364964
MasVnrType      0.382730
BsmtFinType1    0.384000
BsmtFinSF1      0.398335
KitchenQual     0.448447
FireplaceQu     0.463195
Foundation      0.463273
GarageYrBlt     0.468348
MasVnrArea      0.472504
Fireplaces      0.475610
YearRemodAdd    0.510283
YearBuilt       0.542773
TotRmsAbvGrd    0.555989
FullBath        0.570163
ExterQual       0.574934
1stFlrSF        0.611725
TotalBsmtSF     0.612676
GarageArea      0.626319
GarageCars      0.634395
GrLivArea       0.719985
OverallQual     0.789634
SalePrice       1.000000
Name: SalePrice, dtype: float64

In [ ]:
train_data.dtypes

LotFrontage     float64
LotArea           int64
LotShape          int64
OverallQual       int64
YearBuilt         int64
YearRemodAdd      int64
MasVnrType        int64
MasVnrArea      float64
ExterQual         int64
Foundation        int64
BsmtQual          int64
BsmtFinType1      int64
BsmtFinSF1        int64
TotalBsmtSF       int64
HeatingQC         int64
CentralAir        int64
Electrical        int64
1stFlrSF          int64
2ndFlrSF          int64
GrLivArea         int64
FullBath          int64
HalfBath          int64
KitchenQual       int64
TotRmsAbvGrd      int64
Fireplaces        int64
FireplaceQu       int64
GarageType        int64
GarageYrBlt     float64
GarageFinish      int64
GarageCars        int64
GarageArea        int64
GarageQual        int64
GarageCond        int64
WoodDeckSF        int64
OpenPorchSF       int64
SalePrice         int64
dtype: object

In [ ]:
def test_data_prediction(test_data):


  test_data['MSZoning'] = np.where(test_data['MSZoning'] == 'RL', 0, test_data['MSZoning'])
  test_data['MSZoning'] = np.where(test_data['MSZoning'] == 'RM', 1, test_data['MSZoning'])
  test_data['MSZoning'] = np.where(test_data['MSZoning'] == 'FV', 2, test_data['MSZoning'])
  test_data['MSZoning'] = np.where(test_data['MSZoning'] == 'RH', 3, test_data['MSZoning'])
  test_data['MSZoning'] = np.where(test_data['MSZoning'] == 'C (all)', 4, test_data['MSZoning'])




  test_data['MasVnrArea'].fillna(test_data['MasVnrArea'].mean(), inplace=True)


  test_data['GarageYrBlt'].fillna(test_data['GarageYrBlt'].mean(), inplace=True)


  test_data['LotFrontage'].fillna(test_data['LotFrontage'].mean(), inplace=True)


  test_data['Street'] = np.where(test_data['Street'] == 'Pave', 0, test_data['Street'])
  test_data['Street'] = np.where(test_data['Street'] == 'Grvl', 1, test_data['Street'])


  test_data['LotShape'] = np.where(test_data['LotShape'] == 'Reg', 0, test_data['LotShape'])
  test_data['LotShape'] = np.where(test_data['LotShape'] == 'IR1', 1, test_data['LotShape'])
  test_data['LotShape'] = np.where(test_data['LotShape'] == 'IR2', 2, test_data['LotShape'])
  test_data['LotShape'] = np.where(test_data['LotShape'] == 'IR3', 3, test_data['LotShape'])


  test_data['LandContour'] = np.where(test_data['LandContour'] == 'Lvl', 0, test_data['LandContour'])
  test_data['LandContour'] = np.where(test_data['LandContour'] == 'Bnk', 1, test_data['LandContour'])
  test_data['LandContour'] = np.where(test_data['LandContour'] == 'HLS', 2, test_data['LandContour'])
  test_data['LandContour'] = np.where(test_data['LandContour'] == 'Low', 3, test_data['LandContour'])


  test_data['LotConfig'] = np.where(test_data['LotConfig'] == 'Inside', 0, test_data['LotConfig'])
  test_data['LotConfig'] = np.where(test_data['LotConfig'] == 'Corner', 1, test_data['LotConfig'])
  test_data['LotConfig'] = np.where(test_data['LotConfig'] == 'CulDSac', 2, test_data['LotConfig'])
  test_data['LotConfig'] = np.where(test_data['LotConfig'] == 'FR2', 3, test_data['LotConfig'])
  test_data['LotConfig'] = np.where(test_data['LotConfig'] == 'FR3', 4, test_data['LotConfig'])


  test_data['LandSlope'] = np.where(test_data['LandSlope'] == 'Gtl', 0, test_data['LandSlope'])
  test_data['LandSlope'] = np.where(test_data['LandSlope'] == 'Mod', 1, test_data['LandSlope'])
  test_data['LandSlope'] = np.where(test_data['LandSlope'] == 'Sev', 2, test_data['LandSlope'])


  test_data['Neighborhood'] = np.where(test_data['Neighborhood'] == 'NAmes', 0, test_data['Neighborhood'])
  test_data['Neighborhood'] = np.where(test_data['Neighborhood'] == 'CollgCr', 1, test_data['Neighborhood'])
  test_data['Neighborhood'] = np.where(test_data['Neighborhood'] == 'Edwards', 2, test_data['Neighborhood'])
  test_data['Neighborhood'] = np.where(test_data['Neighborhood'] == 'OldTown', 3, test_data['Neighborhood'])
  test_data['Neighborhood'] = np.where(test_data['Neighborhood'] == 'Somerst', 4, test_data['Neighborhood'])
  test_data['Neighborhood'] = np.where(test_data['Neighborhood'] == 'Sawyer', 5, test_data['Neighborhood'])
  test_data['Neighborhood'] = np.where(test_data['Neighborhood'] == 'NridgHt', 6, test_data['Neighborhood'])
  test_data['Neighborhood'] = np.where(test_data['Neighborhood'] == 'Gilbert', 7, test_data['Neighborhood'])
  test_data['Neighborhood'] = np.where(test_data['Neighborhood'] == 'NWAmes', 8, test_data['Neighborhood'])
  test_data['Neighborhood'] = np.where(test_data['Neighborhood'] == 'SawyerW', 9, test_data['Neighborhood'])
  test_data['Neighborhood'] = np.where(test_data['Neighborhood'] == 'BrkSide', 10, test_data['Neighborhood'])
  test_data['Neighborhood'] = np.where(test_data['Neighborhood'] == 'Crawfor', 11, test_data['Neighborhood'])
  test_data['Neighborhood'] = np.where(test_data['Neighborhood'] == 'Mitchel', 12, test_data['Neighborhood'])
  test_data['Neighborhood'] = np.where(test_data['Neighborhood'] == 'Timber', 13, test_data['Neighborhood'])
  test_data['Neighborhood'] = np.where(test_data['Neighborhood'] == 'IDOTRR', 14, test_data['Neighborhood'])
  test_data['Neighborhood'] = np.where(test_data['Neighborhood'] == 'NoRidge', 15, test_data['Neighborhood'])
  test_data['Neighborhood'] = np.where(test_data['Neighborhood'] == 'ClearCr', 16, test_data['Neighborhood'])
  test_data['Neighborhood'] = np.where(test_data['Neighborhood'] == 'SWISU', 17, test_data['Neighborhood'])
  test_data['Neighborhood'] = np.where(test_data['Neighborhood'] == 'StoneBr', 18, test_data['Neighborhood'])
  test_data['Neighborhood'] = np.where(test_data['Neighborhood'] == 'Blmngtn', 19, test_data['Neighborhood'])
  test_data['Neighborhood'] = np.where(test_data['Neighborhood'] == 'MeadowV', 20, test_data['Neighborhood'])
  test_data['Neighborhood'] = np.where(test_data['Neighborhood'] == 'BrDale', 21, test_data['Neighborhood'])
  test_data['Neighborhood'] = np.where(test_data['Neighborhood'] == 'Veenker', 22, test_data['Neighborhood'])
  test_data['Neighborhood'] = np.where(test_data['Neighborhood'] == 'NPkVill', 23, test_data['Neighborhood'])
  test_data['Neighborhood'] = np.where(test_data['Neighborhood'] == 'Blueste', 24, test_data['Neighborhood'])

  test_data['Condition1'] = np.where(test_data['Condition1'] == 'Norm', 0, test_data['Condition1'])
  test_data['Condition1'] = np.where(test_data['Condition1'] == 'Feedr', 1, test_data['Condition1'])
  test_data['Condition1'] = np.where(test_data['Condition1'] == 'Artery', 2, test_data['Condition1'])
  test_data['Condition1'] = np.where(test_data['Condition1'] == 'RRAn', 3, test_data['Condition1'])
  test_data['Condition1'] = np.where(test_data['Condition1'] == 'PosN', 4, test_data['Condition1'])
  test_data['Condition1'] = np.where(test_data['Condition1'] == 'RRAe', 5, test_data['Condition1'])
  test_data['Condition1'] = np.where(test_data['Condition1'] == 'PosA', 6, test_data['Condition1'])
  test_data['Condition1'] = np.where(test_data['Condition1'] == 'RRNn', 7, test_data['Condition1'])
  test_data['Condition1'] = np.where(test_data['Condition1'] == 'RRNe', 8, test_data['Condition1'])


  test_data['Condition2'] = np.where(test_data['Condition2'] == 'Norm', 0, test_data['Condition2'])
  test_data['Condition2'] = np.where(test_data['Condition2'] == 'Feedr', 1, test_data['Condition2'])
  test_data['Condition2'] = np.where(test_data['Condition2'] == 'Artery', 2, test_data['Condition2'])
  test_data['Condition2'] = np.where(test_data['Condition2'] == 'RRAn', 3, test_data['Condition2'])
  test_data['Condition2'] = np.where(test_data['Condition2'] == 'PosN', 4, test_data['Condition2'])
  test_data['Condition2'] = np.where(test_data['Condition2'] == 'RRAe', 5, test_data['Condition2'])
  test_data['Condition2'] = np.where(test_data['Condition2'] == 'PosA', 6, test_data['Condition2'])
  test_data['Condition2'] = np.where(test_data['Condition2'] == 'RRNn', 7, test_data['Condition2'])
  test_data['Condition2'] = np.where(test_data['Condition2'] == 'RRNe', 8, test_data['Condition2'])


  test_data['BldgType'] = np.where(test_data['BldgType'] == '1Fam', 0, test_data['BldgType'])
  test_data['BldgType'] = np.where(test_data['BldgType'] == 'TwnhsE', 1, test_data['BldgType'])
  test_data['BldgType'] = np.where(test_data['BldgType'] == 'Duplex', 2, test_data['BldgType'])
  test_data['BldgType'] = np.where(test_data['BldgType'] == 'Twnhs', 3, test_data['BldgType'])
  test_data['BldgType'] = np.where(test_data['BldgType'] == '2fmCon', 4, test_data['BldgType'])


  test_data['HouseStyle'] = np.where(test_data['HouseStyle'] == '1Story', 0, test_data['HouseStyle'])
  test_data['HouseStyle'] = np.where(test_data['HouseStyle'] == '2Story', 1, test_data['HouseStyle'])
  test_data['HouseStyle'] = np.where(test_data['HouseStyle'] == '1.5Fin', 2, test_data['HouseStyle'])
  test_data['HouseStyle'] = np.where(test_data['HouseStyle'] == 'SLvl', 3, test_data['HouseStyle'])
  test_data['HouseStyle'] = np.where(test_data['HouseStyle'] == 'SFoyer', 4, test_data['HouseStyle'])
  test_data['HouseStyle'] = np.where(test_data['HouseStyle'] == '1.5Unf', 5, test_data['HouseStyle'])
  test_data['HouseStyle'] = np.where(test_data['HouseStyle'] == '2.5Unf', 6, test_data['HouseStyle'])
  test_data['HouseStyle'] = np.where(test_data['HouseStyle'] == '2.5Fin', 7, test_data['HouseStyle'])


  test_data['RoofStyle'] = np.where(test_data['RoofStyle'] == 'Gable', 0, test_data['RoofStyle'])
  test_data['RoofStyle'] = np.where(test_data['RoofStyle'] == 'Hip', 1, test_data['RoofStyle'])
  test_data['RoofStyle'] = np.where(test_data['RoofStyle'] == 'Flat', 2, test_data['RoofStyle'])
  test_data['RoofStyle'] = np.where(test_data['RoofStyle'] == 'Gambrel', 3, test_data['RoofStyle'])
  test_data['RoofStyle'] = np.where(test_data['RoofStyle'] == 'Mansard', 4, test_data['RoofStyle'])
  test_data['RoofStyle'] = np.where(test_data['RoofStyle'] == 'Shed', 5, test_data['RoofStyle'])


  test_data['RoofMatl'].replace({'CompShg':int(0),'Tar&Grv':int(1),'WdShake':int(2), 'WdShngl':int(3), 'Metal':int(4), 'Membran':int(5), 'ClyTile':int(6), 'Roll':int(7)}, inplace=True)


  test_data['Exterior1st'].replace({'VinylSd':int(0),'HdBoard':int(1),'MetalSd':int(2), 'Wd Sdng':int(3), 'Plywood':int(4), 'CemntBd':int(5), 'BrkFace':int(6), 'WdShing':int(7), 'Stucco':int(8), 'AsbShng':int(9), 'Stone':int(10), 'AsphShn':int(11), 'BrkComm':int(12), 'CBlock':int(13), 'ImStucc':int(14)}, inplace=True)


  test_data['Exterior2nd'].replace({'VinylSd':int(0),'HdBoard':int(1),'MetalSd':int(2), 'Wd Sdng':int(3), 'Plywood':int(4), 'CmentBd':int(5), 'Wd Shng':int(6), 'BrkFace':int(7), 'Stucco':int(8), 'AsbShng':int(9), 'ImStucc':int(10), 'Stone':int(11), 'Brk Cmn':int(12), 'AsphShn':int(13), 'Other':int(14), 'CBlock':int(15)}, inplace=True)


  test_data['MasVnrType'].replace({'None':int(0),'BrkFace':int(1),'Stone':int(2), 'BrkCmn':int(3)}, inplace=True)
  test_data['MasVnrType'].fillna(4, inplace=True)


  test_data['ExterQual'].replace({'TA':int(0),'Gd':int(1),'Ex':int(2), 'Fa':int(3)}, inplace=True)


  test_data['ExterCond'].replace({'TA':int(0),'Gd':int(1),'Fa':int(2), 'Ex':int(3), 'Po':int(4)}, inplace=True)


  test_data['Foundation'].replace({'PConc':int(0),'CBlock':int(1),'BrkTil':int(2), 'Slab':int(3), 'Stone':int(4), 'Wood':int(5)}, inplace=True)


  test_data['BsmtQual'].replace({'TA':int(0),'Gd':int(1),'Ex':int(2), 'Fa':int(3)}, inplace=True)
  test_data['BsmtQual'].fillna(4, inplace=True)


  test_data['BsmtCond'].replace({'TA':int(0),'Gd':int(1),'Fa':int(2), 'Po':int(3)}, inplace=True)
  test_data['BsmtCond'].fillna(4, inplace=True)


  test_data['BsmtExposure'].replace({'No':int(0),'Av':int(1),'Gd':int(2), 'Mn':int(3)}, inplace=True)
  test_data['BsmtExposure'].fillna(4, inplace=True)


  test_data['BsmtFinType1'].replace({'GLQ':int(0),'Unf':int(1),'ALQ':int(2), 'BLQ':int(3), 'Rec':int(4), 'LwQ':int(5)}, inplace=True)
  test_data['BsmtFinType1'].fillna(6, inplace=True)


  test_data['BsmtFinType2'].replace({'GLQ':int(0),'Unf':int(1),'ALQ':int(2), 'BLQ':int(3), 'Rec':int(4), 'LwQ':int(5)}, inplace=True)
  test_data['BsmtFinType2'].fillna(6, inplace=True)


  test_data['Heating'] = np.where(test_data['Heating'] == 'GasA', 0, test_data['Heating'])
  test_data['Heating'] = np.where(test_data['Heating'] == 'GasW', 1, test_data['Heating'])
  test_data['Heating'] = np.where(test_data['Heating'] == 'Grav', 2, test_data['Heating'])
  test_data['Heating'] = np.where(test_data['Heating'] == 'Wall', 3, test_data['Heating'])
  test_data['Heating'] = np.where(test_data['Heating'] == 'OthW', 4, test_data['Heating'])
  test_data['Heating'] = np.where(test_data['Heating'] == 'Floor', 5, test_data['Heating'])


  test_data['HeatingQC'] = np.where(test_data['HeatingQC'] == 'Ex', 0, test_data['HeatingQC'])
  test_data['HeatingQC'] = np.where(test_data['HeatingQC'] == 'TA', 1, test_data['HeatingQC'])
  test_data['HeatingQC'] = np.where(test_data['HeatingQC'] == 'Gd', 2, test_data['HeatingQC'])
  test_data['HeatingQC'] = np.where(test_data['HeatingQC'] == 'Fa', 3, test_data['HeatingQC'])
  test_data['HeatingQC'] = np.where(test_data['HeatingQC'] == 'Po', 4, test_data['HeatingQC'])


  test_data['CentralAir'] = np.where(test_data['CentralAir'] == 'Y', 0, test_data['CentralAir'])
  test_data['CentralAir'] = np.where(test_data['CentralAir'] == 'N', 1, test_data['CentralAir'])


  test_data['Electrical'] = np.where(test_data['Electrical'] == 'SBrkr', 0, test_data['Electrical'])
  test_data['Electrical'] = np.where(test_data['Electrical'] == 'FuseA', 1, test_data['Electrical'])
  test_data['Electrical'] = np.where(test_data['Electrical'] == 'FuseF', 2, test_data['Electrical'])
  test_data['Electrical'] = np.where(test_data['Electrical'] == 'FuseP', 3, test_data['Electrical'])
  test_data['Electrical'] = np.where(test_data['Electrical'] == 'Mix', 4, test_data['Electrical'])
  test_data['Electrical'].fillna(5, inplace=True)


  test_data['KitchenQual'] = np.where(test_data['KitchenQual'] == 'TA', 0, test_data['KitchenQual'])
  test_data['KitchenQual'] = np.where(test_data['KitchenQual'] == 'Gd', 1, test_data['KitchenQual'])
  test_data['KitchenQual'] = np.where(test_data['KitchenQual'] == 'Ex', 2, test_data['KitchenQual'])
  test_data['KitchenQual'] = np.where(test_data['KitchenQual'] == 'Fa', 3, test_data['KitchenQual'])


  test_data['Functional'] = np.where(test_data['Functional'] == 'Typ', 0, test_data['Functional'])
  test_data['Functional'] = np.where(test_data['Functional'] == 'Min2', 1, test_data['Functional'])
  test_data['Functional'] = np.where(test_data['Functional'] == 'Min1', 2, test_data['Functional'])
  test_data['Functional'] = np.where(test_data['Functional'] == 'Mod', 3, test_data['Functional'])
  test_data['Functional'] = np.where(test_data['Functional'] == 'Maj1', 4, test_data['Functional'])
  test_data['Functional'] = np.where(test_data['Functional'] == 'Maj2', 5, test_data['Functional'])
  test_data['Functional'] = np.where(test_data['Functional'] == 'Sev', 6, test_data['Functional'])


  test_data['FireplaceQu'].replace({'Gd':int(0),'TA':int(1),'Fa':int(2), 'Ex':int(3), 'Po':int(4)}, inplace=True)
  test_data['FireplaceQu'].fillna(5, inplace=True)


  test_data['GarageType'] = np.where(test_data['GarageType'] == 'Attchd', 0, test_data['GarageType'])
  test_data['GarageType'] = np.where(test_data['GarageType'] == 'Detchd', 1, test_data['GarageType'])
  test_data['GarageType'] = np.where(test_data['GarageType'] == 'BuiltIn', 2, test_data['GarageType'])
  test_data['GarageType'] = np.where(test_data['GarageType'] == 'Basment', 3, test_data['GarageType'])
  test_data['GarageType'] = np.where(test_data['GarageType'] == 'CarPort', 4, test_data['GarageType'])
  test_data['GarageType'] = np.where(test_data['GarageType'] == '2Types', 5, test_data['GarageType'])
  test_data['GarageType'].fillna(6, inplace=True)


  test_data['GarageFinish'] = np.where(test_data['GarageFinish'] == 'Unf', 0, test_data['GarageFinish'])
  test_data['GarageFinish'] = np.where(test_data['GarageFinish'] == 'RFn', 1, test_data['GarageFinish'])
  test_data['GarageFinish'] = np.where(test_data['GarageFinish'] == 'Fin', 2, test_data['GarageFinish'])
  test_data['GarageFinish'].fillna(3, inplace=True)


  test_data['GarageQual'].replace({'TA':int(0),'Fa':int(1),'Gd':int(2), 'Po':int(3), 'Ex': int(4)}, inplace=True)
  test_data['GarageQual'].fillna(5, inplace=True)


  test_data['GarageCond'].replace({'TA':int(0),'Fa':int(1),'Gd':int(2), 'Po':int(3), 'Ex': int(4)}, inplace=True)
  test_data['GarageCond'].fillna(5, inplace=True)


  test_data['PavedDrive'].replace({'Y':int(0),'N':int(1),'P':int(2)}, inplace=True)


  test_data['Fence'].replace({'MnPrv':int(0),'GdWo':int(1),'GdPrv':int(2), 'MnWw':int(3),}, inplace=True)
  test_data['Fence'].fillna(4, inplace=True)


  test_data['SaleType'].replace({'WD':int(0),'New':int(1),'COD':int(2), 'CWD':int(3), 'ConLw':int(4), 'ConLD':int(5), 'ConLI':int(6), 'Con':int(7), 'Oth':int(8)}, inplace=True)


  test_data['SaleCondition'].replace({'Normal':int(0),'Partial':int(1),'Abnorml':int(2), 'Family':int(3), 'Alloca':int(4), 'AdjLand':int(5)}, inplace=True)


  test_data['Alley'].replace({'Grvl':int(0),'Pave':int(1)}, inplace=True)
  test_data['Alley'].fillna(2, inplace=True)


  test_data['Utilities'].replace({'AllPub':int(0),'NoSeWa':int(1)}, inplace=True)


  test_data['PoolQC'].replace({'Gd':int(0),'Ex':int(1),'Fa':int(2)}, inplace=True)
  test_data['PoolQC'].fillna(3, inplace=True)


  test_data['MiscFeature'].replace({'Shed':int(0),'Othr':int(1),'Gar2':int(2), 'TenC':int(3)}, inplace=True)
  test_data['MiscFeature'].fillna(3, inplace=True)


  test_data = test_data.astype({'MSZoning': int, 'Street': int, 'LotShape': int, 'LandContour': int,
                                  'LotConfig': int, 'LandSlope': int, 'Neighborhood': int, 'Condition1': int, 'Condition2': int,
                                  'BldgType': int, 'HouseStyle': int, 'RoofStyle': int,
                                  'RoofMatl': int, 'Exterior1st': int, 'Exterior2nd': int, 'MasVnrType': int, 'ExterQual': int,
                                  'ExterCond': int, 'Foundation': int, 'BsmtQual': int, 'BsmtCond': int, 'BsmtExposure': int, 'BsmtFinType1': int,
                                  'BsmtFinType2': int, 'Heating': int, 'HeatingQC': int, 'CentralAir': int,
                                  'Electrical': int, 'KitchenQual': int, 'Functional': int, 'FireplaceQu': int,
                                  'GarageType': int, 'GarageFinish': int, 'GarageQual': int, 'GarageCond': int,
                                  'PavedDrive': int, 'Fence': int, 'SaleType': int, 'SaleCondition': int, 'Alley': int}, errors = 'ignore')


  test_data=test_data.drop(['Utilities', 'Id', 'Unnamed: 0', 'PoolQC', 'BsmtFinSF2', 'BsmtHalfBath', 'YrSold', 'MiscVal',
                              '3SsnPorch', 'SaleCondition', 'MoSold', 'BsmtFinType2', 'MSSubClass', 'LowQualFinSF', 'OverallCond',
                              'Fence', 'SaleType', 'RoofMatl', 'BsmtCond', 'ScreenPorch', 'PoolArea', 'BsmtFullBath',
                              'EnclosedPorch', 'Condition2', 'Street', 'LandSlope', 'BsmtExposure', 'Alley', 'PavedDrive', 'BsmtUnfSF',
                              'Condition1', 'LandContour', 'LotConfig', 'HouseStyle', 'Heating', 'Functional', 'KitchenAbvGr',
                              'Exterior2nd', 'Exterior1st', 'ExterCond', 'Neighborhood', 'RoofStyle', 'BldgType', 'BedroomAbvGr',
                              'MSZoning', 'MiscFeature'],axis=1)
  return

Training the Train data

In [ ]:
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from mlxtend.classifier import StackingCVClassifier
from sklearn.model_selection import GridSearchCV

# define X and y
X = train_data.drop('SalePrice', axis=1)
y = train_data['SalePrice']

# split the data into train and test sets
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# perform kmeans clustering
kmeans = KMeans(n_clusters=4, random_state=42)
clusters = kmeans.fit_predict(X)#_train)

# list to store the best models for each group
best_models = []

# list to store the best model scores for each group
best_scores = []

# initialize the models
clf1 = KNeighborsClassifier(n_jobs=-1)
clf2 = RandomForestClassifier(n_jobs=-1)
clf3 = AdaBoostClassifier()
clf4 = GaussianProcessClassifier(n_jobs=-1)
clf5 = GradientBoostingClassifier()
clf6 = DecisionTreeClassifier()
lr = LogisticRegression(max_iter=1000, n_jobs=-1)
svm_model = SVC()

# define the models for grid search
models = [clf1, clf2, clf3, clf4]#, clf5, clf6, lr, svm_model]

# define the parameter grid
param_grid = {'kneighborsclassifier__n_neighbors': [1, 10],
              'randomforestclassifier__n_estimators': [1, 10],
              'gaussianprocessclassifier__n_restarts_optimizer': [1, 10]}
              #'gradientboostingclassifier__n_estimators': [1, 10],
              #'logisticregression__C': [0.1, 1.0],
              #'svc__C': [0.1, 1.0]}

# perform grid search and cross-validation for each cluster
for i in range(4):
    # filter data based on the cluster
    X_train_cluster = X[clusters == i]#_train
    y_train_cluster = y[clusters == i]#_train
    print(f"Class {i}")

    # count the number of samples in each class
    unique, counts = np.unique(y_train_cluster, return_counts=True)
    print("Class Counts:", dict(zip(unique, counts)))

    # continue with the next class if there are not enough samples
    try:

        sclf = StackingCVClassifier(classifiers=models,
                                meta_classifier=lr,
                                random_state=42)

        # initialize the grid search
        grid = GridSearchCV(estimator = sclf,
                            param_grid=param_grid,
                            cv=2,
                            refit=True)

        # fit the grid search
        grid.fit(X_train_cluster, y_train_cluster)

        cv_keys = ('mean_test_score', 'std_test_score', 'params')

        for r, _ in enumerate(grid.cv_results_['mean_test_score']):
            print("%0.3f +/- %0.2f %r"
                  % (grid.cv_results_[cv_keys[0]][r],
                    grid.cv_results_[cv_keys[1]][r] / 2.0,
                    grid.cv_results_[cv_keys[2]][r]))

        print('Best parameters: %s' % grid.best_params_)
        print('Accuracy: %.2f' % grid.best_score_)


        # append the best model and score to the respective lists
        best_models.append(grid.best_estimator_)
        best_scores.append(grid.best_score_)
    except:
        best_models.append(None)
        best_scores.append(0)

# define the stacking classifier
sclf = StackingCVClassifier(classifiers=models,
                             meta_classifier=RandomForestClassifier(n_jobs=-1),
                             random_state=42)

# fit the stacking classifier
sclf.fit(X, y)

test_data_prediction(test_data)

X_test = test_data.drop('SalePrice', axis=1)
y_test = test_data['SalePrice']

sclf.fit(X_test, y_test)
# make predictions on the test set
y_pred = sclf.predict(X_test)

# calculate the accuracy
print("Accuracy:", accuracy_score(y_test, y_pred))

from sklearn.metrics import mean_squared_error

# Calculate MSE
mse = mean_squared_error(y_test, y_pred)

print("Mean Squared Error:", mse)

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

Class 0
Class Counts: {35311: 1, 37900: 1, 39300: 1, 40000: 1, 52000: 1, 52500: 1, 55000: 2, 55993: 1, 58500: 1, 60000: 2, 61000: 1, 62383: 1, 67000: 1, 68400: 1, 68500: 1, 73000: 1, 75500: 1, 76500: 1, 78000: 1, 79000: 3, 79500: 1, 79900: 1, 80000: 3, 81000: 1, 82000: 2, 83000: 1, 84500: 2, 85000: 2, 85400: 1, 85500: 1, 86000: 2, 87000: 3, 87500: 1, 88000: 3, 89000: 1, 89471: 1, 89500: 2, 90000: 1, 90350: 1, 91000: 3, 91300: 1, 91500: 1, 92000: 1, 92900: 1, 93000: 3, 93500: 1, 95000: 1, 97000: 2, 98000: 3, 98300: 1, 98600: 1, 99900: 1, 100000: 5, 101000: 1, 101800: 1, 102000: 2, 102776: 1, 103000: 1, 103200: 1, 103600: 1, 104000: 1, 104900: 1, 105000: 4, 105500: 1, 105900: 1, 106000: 2, 107000: 3, 107400: 1, 107500: 2, 107900: 1, 108000: 2, 108500: 1, 109000: 1, 109008: 1, 109500: 2, 109900: 3, 110000: 9, 110500: 1, 112000: 4, 112500: 1, 113000: 3, 114500: 2, 114504: 1, 115000: 7, 116000: 2, 116050: 1, 116900: 1, 117000: 2, 117500: 1, 118000: 5, 118400: 1, 118500: 2, 118858: 1, 119000: 2, 119500: 3, 119750: 1, 119900: 2, 120000: 3, 120500: 2, 121600: 1, 122000: 2, 122900: 1, 123000: 3, 124000: 5, 124500: 3, 124900: 2, 125000: 7, 125500: 3, 126000: 3, 126175: 1, 126500: 1, 127000: 7, 127500: 6, 128000: 3, 128500: 3, 128900: 1, 128950: 1, 129000: 7, 129500: 2, 129900: 3, 130000: 11, 130500: 1, 131000: 2, 131500: 1, 132000: 2, 132500: 3, 133000: 5, 133700: 1, 133900: 2, 134000: 2, 134500: 2, 134800: 1, 135000: 6, 135500: 1, 135900: 1, 136000: 3, 136500: 2, 136900: 1, 137000: 1, 137450: 1, 137500: 1, 138000: 1, 138500: 1, 139000: 6, 139400: 1, 139500: 1, 140000: 6, 140200: 1, 141000: 5, 141500: 1, 142000: 2, 142953: 1, 143000: 5, 143250: 1, 143500: 2, 143750: 1, 144000: 4, 144500: 2, 144900: 1, 145000: 8, 145900: 1, 146000: 2, 146500: 1, 147000: 4, 147400: 1, 147500: 1, 148000: 2, 148800: 1, 149000: 3, 149300: 1, 149350: 1, 149500: 1, 149900: 2, 150000: 2, 150500: 1, 150750: 1, 151000: 3, 151400: 1, 152000: 1, 153000: 2, 153575: 1, 153900: 1, 154000: 3, 154500: 1, 154900: 1, 155000: 9, 155900: 1, 156000: 2, 156500: 1, 157000: 1, 157500: 1, 158000: 2, 159000: 2, 159434: 1, 159500: 1, 159895: 1, 160000: 3, 160200: 1, 161000: 2, 162000: 2, 162900: 2, 163000: 2, 163990: 1, 164000: 2, 165000: 5, 165150: 1, 165400: 1, 165500: 2, 165600: 1, 166000: 1, 167000: 3, 167240: 1, 167500: 1, 167900: 2, 168000: 1, 168500: 3, 169000: 2, 169500: 1, 170000: 1, 171000: 2, 171900: 1, 172500: 1, 173000: 4, 173500: 1, 173733: 1, 173900: 1, 174000: 4, 174900: 1, 175000: 3, 175500: 1, 175900: 2, 176000: 5, 176432: 1, 176485: 1, 176500: 1, 177000: 2, 177500: 2, 178000: 3, 179000: 2, 179200: 2, 179400: 1, 179500: 1, 179540: 1, 179600: 1, 179900: 1, 180000: 4, 180500: 1, 181000: 3, 181134: 1, 181500: 1, 183000: 1, 183200: 1, 183500: 1, 183900: 1, 184000: 2, 184100: 1, 184900: 1, 185000: 4, 185500: 1, 185750: 1, 185850: 1, 185900: 1, 186000: 1, 186500: 2, 187000: 2, 187500: 1, 187750: 1, 188500: 1, 189000: 4, 189950: 1, 190000: 3, 191000: 1, 192000: 4, 192500: 1, 193000: 1, 193500: 1, 193879: 1, 194000: 2, 194201: 1, 194500: 1, 194700: 1, 195400: 1, 196000: 2, 197000: 1, 197500: 2, 197900: 1, 198500: 1, 198900: 1, 199900: 1, 200000: 2, 200100: 1, 200500: 1, 201000: 2, 202500: 2, 202665: 1, 204000: 2, 205000: 3, 205950: 1, 206000: 1, 206300: 1, 207500: 2, 208300: 1, 208500: 1, 208900: 1, 209500: 1, 210000: 3, 211000: 2, 212000: 1, 213000: 3, 213250: 1, 213490: 1, 213500: 2, 214000: 3, 215000: 2, 215200: 1, 216500: 1, 216837: 1, 219500: 2, 220000: 3, 222000: 1, 222500: 1, 224900: 1, 225000: 1, 226000: 1, 226700: 1, 227000: 2, 228500: 1, 230000: 3, 232000: 1, 235000: 1, 237000: 2, 239000: 2, 239500: 1, 239799: 1, 239900: 1, 240000: 1, 241000: 1, 241500: 1, 244600: 1, 245000: 1, 246578: 1, 248328: 1, 250000: 1, 250580: 1, 251000: 1, 253000: 1, 254000: 1, 259500: 1, 260000: 1, 262500: 1, 263000: 1, 263435: 1, 264561: 1, 265900: 1, 266000: 1, 266500: 1, 269790: 1, 270000: 1, 274300: 1, 274900: 1, 275000: 1, 275500: 1, 276000: 1, 277500: 1, 278000: 2, 287090: 1, 290000: 2, 293077: 1, 302000: 1, 305900: 1, 307000: 1, 311872: 1, 315000: 1, 317000: 1, 318061: 1, 328900: 1, 337000: 1, 348000: 1, 350000: 1, 370878: 1, 383970: 1, 392500: 1}

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(

0.007 +/- 0.00 {'gaussianprocessclassifier__n_restarts_optimizer': 1, 'kneighborsclassifier__n_neighbors': 1, 'randomforestclassifier__n_estimators': 1}
0.012 +/- 0.00 {'gaussianprocessclassifier__n_restarts_optimizer': 1, 'kneighborsclassifier__n_neighbors': 1, 'randomforestclassifier__n_estimators': 10}
0.007 +/- 0.00 {'gaussianprocessclassifier__n_restarts_optimizer': 1, 'kneighborsclassifier__n_neighbors': 10, 'randomforestclassifier__n_estimators': 1}
0.013 +/- 0.00 {'gaussianprocessclassifier__n_restarts_optimizer': 1, 'kneighborsclassifier__n_neighbors': 10, 'randomforestclassifier__n_estimators': 10}
0.018 +/- 0.00 {'gaussianprocessclassifier__n_restarts_optimizer': 10, 'kneighborsclassifier__n_neighbors': 1, 'randomforestclassifier__n_estimators': 1}
0.007 +/- 0.00 {'gaussianprocessclassifier__n_restarts_optimizer': 10, 'kneighborsclassifier__n_neighbors': 1, 'randomforestclassifier__n_estimators': 10}
0.009 +/- 0.00 {'gaussianprocessclassifier__n_restarts_optimizer': 10, 'kneighborsclassifier__n_neighbors': 10, 'randomforestclassifier__n_estimators': 1}
0.007 +/- 0.00 {'gaussianprocessclassifier__n_restarts_optimizer': 10, 'kneighborsclassifier__n_neighbors': 10, 'randomforestclassifier__n_estimators': 10}
Best parameters: {'gaussianprocessclassifier__n_restarts_optimizer': 10, 'kneighborsclassifier__n_neighbors': 1, 'randomforestclassifier__n_estimators': 1}
Accuracy: 0.02
Class 1
Class Counts: {228950: 1, 375000: 1}
Class 2
Class Counts: {64500: 1, 80000: 1, 82500: 2, 84000: 1, 84500: 1, 84900: 1, 90000: 1, 95000: 1, 97000: 1, 97500: 1, 108000: 1, 108959: 1, 110000: 2, 111250: 1, 112000: 2, 115000: 1, 117000: 1, 118500: 1, 119000: 1, 120000: 1, 121500: 1, 122500: 1, 129500: 1, 130500: 2, 131500: 2, 132250: 1, 132500: 1, 133000: 1, 135000: 3, 136500: 1, 136905: 1, 137000: 2, 137500: 2, 137900: 1, 138800: 1, 139600: 1, 139900: 1, 140000: 3, 141000: 1, 142000: 2, 142500: 1, 142600: 1, 143000: 1, 143900: 1, 144000: 1, 145000: 2, 145250: 1, 146800: 1, 147000: 3, 148000: 2, 149500: 1, 149900: 1, 152000: 3, 153900: 1, 154000: 1, 155000: 1, 155835: 1, 156000: 1, 157000: 3, 157500: 1, 157900: 1, 158000: 3, 158500: 1, 159000: 1, 160000: 1, 161500: 1, 161750: 1, 162000: 1, 162500: 1, 163000: 2, 163500: 1, 164000: 1, 164500: 1, 165000: 1, 165500: 1, 166000: 1, 167000: 1, 167500: 1, 168000: 1, 169000: 1, 169900: 1, 170000: 3, 171000: 2, 172000: 1, 172500: 2, 172785: 1, 173000: 1, 174000: 1, 174500: 1, 175000: 4, 175500: 1, 176000: 1, 177000: 2, 177500: 1, 178000: 1, 178400: 1, 179000: 1, 179665: 1, 179900: 2, 180000: 2, 180500: 2, 181000: 2, 181900: 1, 182000: 1, 182900: 1, 184000: 2, 185000: 3, 187100: 1, 187500: 2, 189000: 1, 190000: 7, 191000: 1, 192140: 1, 192500: 1, 194000: 1, 195000: 1, 197000: 1, 197900: 1, 199900: 1, 200000: 4, 200141: 1, 201800: 1, 202500: 1, 203000: 1, 205000: 1, 206900: 1, 207000: 1, 207500: 1, 210000: 1, 212000: 1, 214000: 1, 214900: 1, 215000: 4, 218000: 1, 219500: 1, 220000: 2, 221500: 1, 222000: 2, 222500: 1, 223000: 1, 223500: 2, 224000: 1, 224500: 1, 225000: 4, 226000: 1, 227680: 1, 228000: 1, 230000: 3, 230500: 1, 231500: 2, 232000: 1, 232600: 1, 235000: 2, 235128: 1, 238000: 1, 239000: 2, 239686: 1, 240000: 2, 242000: 2, 243000: 1, 244000: 2, 244400: 1, 245500: 1, 248900: 1, 249700: 1, 250000: 6, 253293: 1, 254900: 1, 255000: 1, 255900: 1, 256300: 1, 257000: 1, 258000: 1, 260000: 3, 261500: 1, 262280: 1, 262500: 1, 264132: 1, 266000: 1, 267000: 1, 268000: 2, 269500: 1, 270000: 1, 271000: 1, 271900: 1, 274000: 1, 274725: 1, 274970: 1, 275000: 3, 277000: 1, 279500: 1, 280000: 2, 281213: 1, 282922: 1, 283463: 1, 284000: 1, 285000: 1, 287000: 1, 290000: 1, 294000: 1, 297000: 1, 301500: 1, 310000: 2, 311500: 1, 312500: 1, 314813: 1, 315000: 2, 315500: 1, 315750: 1, 316600: 1, 318000: 2, 319000: 1, 320000: 3, 324000: 1, 325000: 3, 325300: 1, 325624: 1, 333168: 1, 335000: 2, 336000: 1, 337500: 1, 339750: 1, 340000: 2, 345000: 2, 354000: 1, 359100: 1, 360000: 1, 369900: 1, 374000: 1, 377426: 1, 380000: 1, 381000: 1, 385000: 1, 386250: 1, 394432: 1, 395000: 1, 402861: 1, 412500: 1, 415298: 1, 426000: 1, 430000: 1, 437154: 1, 438780: 1, 440000: 1, 446261: 1, 465000: 1, 466500: 1, 485000: 1, 501837: 1, 555000: 1, 556581: 1, 582933: 1, 611657: 1, 745000: 1, 755000: 1}

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(

0.003 +/- 0.00 {'gaussianprocessclassifier__n_restarts_optimizer': 1, 'kneighborsclassifier__n_neighbors': 1, 'randomforestclassifier__n_estimators': 1}
0.006 +/- 0.00 {'gaussianprocessclassifier__n_restarts_optimizer': 1, 'kneighborsclassifier__n_neighbors': 1, 'randomforestclassifier__n_estimators': 10}
0.003 +/- 0.00 {'gaussianprocessclassifier__n_restarts_optimizer': 1, 'kneighborsclassifier__n_neighbors': 10, 'randomforestclassifier__n_estimators': 1}
0.009 +/- 0.00 {'gaussianprocessclassifier__n_restarts_optimizer': 1, 'kneighborsclassifier__n_neighbors': 10, 'randomforestclassifier__n_estimators': 10}
0.009 +/- 0.00 {'gaussianprocessclassifier__n_restarts_optimizer': 10, 'kneighborsclassifier__n_neighbors': 1, 'randomforestclassifier__n_estimators': 1}
0.009 +/- 0.00 {'gaussianprocessclassifier__n_restarts_optimizer': 10, 'kneighborsclassifier__n_neighbors': 1, 'randomforestclassifier__n_estimators': 10}
0.009 +/- 0.00 {'gaussianprocessclassifier__n_restarts_optimizer': 10, 'kneighborsclassifier__n_neighbors': 10, 'randomforestclassifier__n_estimators': 1}
0.003 +/- 0.00 {'gaussianprocessclassifier__n_restarts_optimizer': 10, 'kneighborsclassifier__n_neighbors': 10, 'randomforestclassifier__n_estimators': 10}
Best parameters: {'gaussianprocessclassifier__n_restarts_optimizer': 10, 'kneighborsclassifier__n_neighbors': 1, 'randomforestclassifier__n_estimators': 10}
Accuracy: 0.01
Class 3
Class Counts: {160000: 1, 186700: 1, 190000: 1, 215000: 1, 240000: 2, 241500: 1, 256000: 1, 402000: 1, 538000: 1}

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(

Accuracy: 0.0410958904109589
Mean Squared Error: 2155834881.543379